version: '3.8'

services:
  backend:
    image: llm-graph-builder-backend:latest
    container_name: llm-graph-builder-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PORT=8000
    volumes:
      # Persistent data volumes
      - llm_graph_data:/code/data
      - llm_graph_chunks:/code/chunks
      - llm_graph_merged:/code/merged_files
      - llm_graph_logs:/code/logs
      - llm_graph_cache:/code/cache
      - llm_graph_uploads:/code/uploads
      - llm_graph_models:/code/models
      - llm_graph_temp:/code/temp
      
      # Optional: Mount local directories for development
      # - ./data:/code/data
      # - ./chunks:/code/chunks
      # - ./merged_files:/code/merged_files
      # - ./logs:/code/logs
      # - ./cache:/code/cache
      # - ./uploads:/code/uploads
      # - ./models:/code/models
      # - ./temp:/code/temp
      
      # Configuration files (read-only)
      - ./example.env:/code/example.env:ro
      
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'

volumes:
  # Persistent data volumes
  llm_graph_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
  llm_graph_chunks:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./chunks
  llm_graph_merged:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./merged_files
  llm_graph_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./logs
  llm_graph_cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./cache
  llm_graph_uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./uploads
  llm_graph_models:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./models
  llm_graph_temp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./temp
