version: '3.8'

services:
  backend:
    image: llm-graph-builder-backend:latest
    container_name: llm-graph-builder-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PORT=8000
    volumes:
      # Optional: Mount a local directory for file processing
      - ./chunks:/code/chunks
      - ./merged_files:/code/merged_files
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
